---
title: "Pricing Analysis - Sell in"
output: html_document
---
```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE,# Prevents code but not the results
                      message = FALSE,
                      warning = FALSE)

knitr::opts_knit$set(root.dir = dirname(rstudioapi::getActiveDocumentContext()$path))
# https://towardsdatascience.com/five-r-markdown-tricks-that-you-may-not-know-about-71e93f50c026
```



```{r librerias}
library(odbc)
library(lares)
library(readxl)
library(rattle)
library(ggtext)
library(stringr)
library(ggplot2)
library(ggrepel)
library(magrittr)
library(tidyverse)
library(lubridate)
library(patchwork)
library(ggfittext)
library(data.table)
library(kableExtra)
library(formattable)
library(DataExplorer)
library(summarytools)
library(tidylog) # tidy log necesariamente tiene que estar despues de dplyr y tidyr


```


```{r coneccion}

# con <- DBI::dbConnect(odbc(),
#                       Driver = "SQL Server",
#                       Server = "10.110.20.59",
#                       Database = "contactabilidad_ic",
#                       UID = "user_ic",
#                       PWD = "Derco.2020")


# importador <- dbGetQuery(conn = con,"SELECT * FROM procesos_sap_bwp.[dbo].facturacion_importador_ZVMS_CP001_Q014_DL")


# importador %>% write_rds("01.Data/Base_importador.rds")


```


```{r}

setwd("C:/Users/dincappuenot/OneDrive - Grupo Derco/Escritorio/Pricing Analysis/")

sell_in <- read_excel("01.Data/AFO Ventas Unidades Importador BI Ene'22_PRECIOS.xlsx",range = "A2:AH50059",sheet = "Hoja1")

importador  <- read_rds("01.Data/Base_importador.rds")

```

```{r importador}

importador <- importador %>%
  select(vin,fecha_facturacion,modelo) %>% 
  group_by(vin) %>%
  arrange(desc(fecha_facturacion)) %>%
  slice(1)
  
importador %<>% filter(vin!="#")

importador$fecha_facturacion <- NULL

```


```{r}

sell_in %>% glimpse

names(sell_in) %<>% normVarNames()

sell_in %<>% rename(version=modelo,
                    anio_modelo=año_modelo,
                    marca=marca_derco,
                    fecha_facturacion=fecha_de_facturación,
                    tipo_factura=y)

sell_in$fecha_facturacion %<>% ymd()

sell_in$factura_sap %<>% as.numeric()

sell_in %<>% filter(folio_legal_factura!="0000000000000000")
# sell_in %<>% filter(!clase_de_factura %in% c("S1","S2"))

summary_by_vin <- sell_in %>% 
  group_by(niv) %>% 
  summarise(n_registros=n(),
            suma_unidades=sum(cantidad),
            total_precio_lista=sum(precio_lista))

# summary_by_vin %>% 
#   crosstab(n_registros,suma_unidades)

summary_by_vin %$% 
  table(n_registros,suma_unidades,useNA = "ifany") %>% 
  margin.table(2) %>% 
  prop.table() %>% 
  round(4)*100

# Los que suma -1 y 0 en unidades se excluyen ya que no son ventas.
# Los que suma >1 se excluyen por aun no determinar el significado de mas de 1 registro con unidad=1, ademas que ocupan un 0.14% de la data

selected_vin <- summary_by_vin %>% 
  filter(suma_unidades==1) %>% 
  pull(niv)


sell_in <- sell_in %>% 
  filter(niv %in% selected_vin) %>% 
  group_by(niv) %>% 
  arrange(desc(factura_sap)) %>% 
  slice(1) %>% 
  ungroup() %>% 
  filter(cantidad==1)# Hay algunas ultimas facturas que tienen -1 -> son considerados no ventas


sell_in %>% glimpse

```



```{r ISC}

isc <- read_excel("01.Data/Lista_precios_2021/Ajustado/ISC/Lista ISC.xlsx",
                  range = "A1:B348")

isc1 <- read_excel("01.Data/Lista_precios_2021/Ajustado/ISC/Lista de Vehiculos sin ISC - suzuki.xlsx",col_types = rep("text",5))

isc2 <- read_excel("01.Data/Lista_precios_2021/Ajustado/ISC/Lista de Vehiculos sin ISC - changan,citroen,mazda.xlsx",col_types = rep("text",5))
isc2 %>% head

isc3 <- read_excel("01.Data/Lista_precios_2021/Ajustado/ISC/Lista de Vehiculos sin ISC- RENAULT.xlsx",col_types = rep("text",5))

isc4 <- read_excel("01.Data/Lista_precios_2021/Ajustado/ISC/lista vehiculos restantes (003).xlsx",col_types = rep("text",6))
isc4 %>% head

#ISC
names(isc) %<>% normVarNames()

isc %<>% filter(!is.na(codigo_sap_unidades_derco))

isc$codigo_sap_unidades_derco %<>% str_to_upper()
sell_in$cod_modelo %<>% str_to_upper()
names(isc) <- c("cod_modelo","isc")


#ISC1
isc1 %<>% filter(!is.na(isc)) %>%  select(cod_modelo,isc)
isc1$isc %<>% as.numeric

#ISC2
names(isc2) %<>% normVarNames()
isc2 %<>% filter(!is.na(isc)) %>%  select(cod_modelo,isc)
isc2$isc %<>% as.numeric

#ISC3
names(isc3) %<>% normVarNames()
isc3 %<>% rename(isc=x)
isc3 %<>% filter(!is.na(isc)) %>%  select(cod_modelo,isc)
isc3$isc %<>% as.numeric

#ISC4
names(isc4) %<>% normVarNames()
isc4 %<>% filter(!is.na(isc)) %>%  select(cod_modelo,isc)
isc4$isc %<>% as.numeric


#ISC GLOBAL
isc_global <- bind_rows(isc,isc1,isc2,isc3,isc4) %>% 
  filter(!is.na(cod_modelo)) %>%  
  distinct()

isc_global$isc %>% summary

```

```{r join-isc-sell-in}

sell_in <- sell_in %>% left_join(isc_global,by=c("cod_modelo"))

sell_in %>%
  filter(is.na(isc)) %>%
  select(marca,version,cod_modelo) %>%
  distinct %>% nrow
#   write.csv("Lista de Vehiculos sin ISC.csv")

# prueba %>% 
  # filter(precio_lista<1000) %>% 
  # pull(precio_lista) %>% summary

# prueba %>% 
#   filter(precio_lista<1000) %>% 
#   select(precio_lista,everything()) %>% 
#   write.csv("Lista de Vehiculos Precio de Lista menor a 1000.csv")

```



```{r join-importador}
sell_in <- sell_in %>% left_join(importador,by=c("niv"="vin"))

# prueba %>%
#   filter(is.na(isc)) %>% 
#   distinct(cod_modelo,marca_derco,modelo,version) %>% 
#   write.csv("lista vehiculos restantes.csv")
```

```{r filtros-data}

# ISC
sell_in %<>% filter(!is.na(isc))

# Anio_Modelo
sell_in %>% crosstab(anio_modelo)

sell_in %<>% filter(anio_modelo>=2020)

# modelo

sell_in %<>% filter(!is.na(modelo))

# Tipo Factura
sell_in %<>% filter(!tipo_factura %in% c("Fac. Unid.Extranjero","Anulación de abono","Fact.Titulo Gratuito"))

# # Ventas

sell_in %>% 
  mutate(periodo_facturacion=format(fecha_facturacion,"%Y%m")) %>% 
  crosstab(periodo_facturacion) %>% 
  ggplot(aes(x=periodo_facturacion,y=n))+
  geom_bar(stat="identity")

sell_in %>% filter(fecha_facturacion>="2020-07-01")

# Precios 

sell_in %<>% filter(precio_lista!=0)
# sell_in$precio_lista %>% quantile(probs=seq(0,1,.01))

```


```{r precio-sap}
sell_in$precio_sap <- sell_in %$% (precio_lista*(1+isc)*(1.18))

# sell_in %>% 
#   select(precio_lista,isc,precio_sap)

# 24568*1.18

# Retiro de Año Modeo

```

```{r all-autos}

modelos <- sell_in %>% 
  group_by(modelo) %>% 
  nest()

modelos %<>% 
  mutate(ventas_totales=map_dbl(data,nrow)) %>% 
  arrange(desc(ventas_totales))

modelos <- modelos %>% 
  dplyr::mutate(elasticidad_df = map(data, function(x) x %>% 
                          dplyr::mutate(periodo_facturacion = format(fecha_facturacion,"%Y%m") ) %>% 
                          group_by(periodo_facturacion) %>% 
                          summarise(ventas=n(),
                                    precio_promedio=median(precio_sap),
                                    precio_cv=sd(precio_sap)/mean(precio_sap)) %>% 
                          ungroup() %>% 
                          dplyr::mutate(fecha_facturacion = ymd(paste0(periodo_facturacion,"01") ) ) %>% 
                          dplyr::mutate(precio_cv = percent(precio_cv)  ) %>% 
                          filter(ventas>=3)
                          ),
         n_periodos = map_dbl(elasticidad_df,nrow)) 

modelos %<>% 
  mutate(cor=map_dbl(elasticidad_df,function(x) cor(x$ventas,x$precio_promedio) ))

modelos %<>% 
  mutate(ventas_periodo = ventas_totales/n_periodos)

modelos %<>% 
  mutate(flag_12 = ifelse(n_periodos>=12,"Si","No"))


```



```{r all-autos-matriz-ventas-correlacion}

require(ggthemes)

modelos$n_periodos %>% summary

modelos %>% 
  ggplot(aes(x=cor,y=ventas_periodo,shape=flag_12,color=flag_12))+
  geom_point(size=5)+
  geom_vline(xintercept = 0,linetype="dashed",color="gray50",size=1.5)+
  # ylim(0,15)+
  theme_bw()+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text = element_text(size=15),
        axis.title = element_text(size=15),
        title = element_text(size=18),
        plot.title.position = "plot",
        legend.position = "bottom")+
  labs(x="NIVEL DE CORRELACION",
       y="FRECUENCIA DE VENTAS/MES",
       color="Participacion >= 12 Meses",
       shape="Participacion >= 12 Meses",
       title = "Relacion de Correlacion(Precio & Ventas) vs Frecuencia de Ventas/Mes")

modelos$flag_12 %>% unique
modelos$cor %>% unique

modelos %>% 
  filter(flag_12=="Si",
         cor<0) %>% nrow

```


```{r all-autos-correlacion}
# Correlacion Positiva

modelos %>% 
  # filter(cor>0.8) %>% 
  arrange(desc(cor)) %>% 
  head(4) %>% 
  unnest(elasticidad_df) %>% 
  ggplot(aes(x=ventas,y=precio_promedio))+
  geom_point(color="gray50",size=5)+
  geom_line(color="steelblue3",size=2)+
  # scale_y_continuous(breaks=seq(3,9),labels=seq(3,9))+
  scale_y_continuous(labels = scales::label_number(suffix = "k", scale = 1e-3, decimal.mark =  ".",accuracy = .1))+
  facet_wrap(~modelo,nrow = 2,scales = "free")+
  theme_bw()+
  theme(strip.text = element_text(face = "bold",color="white"),
        strip.background = element_rect(fill="#1B9E77"),
        axis.text = element_text(size=10))+
  labs(y="PRECIO PROMEDIO",x="VENTAS")

# Correlacion Negativa
modelos %>% 
  arrange(cor) %>% 
  head(4) %>% 
  unnest(elasticidad_df) %>% 
  ggplot(aes(x=ventas,y=precio_promedio))+
  geom_point(color="gray50",size=5)+
  geom_line(color="steelblue3",size=2)+
  # scale_y_continuous(breaks=seq(3,9),labels=seq(3,9))+
  # scale_x_continuous(labels = comma)+
  scale_y_continuous(labels = scales::label_number(suffix = "k", scale = 1e-3, decimal.mark =  ".",accuracy = .1))+
  facet_wrap(~modelo,nrow = 2,scales = "free")+
  theme_bw()+
  theme(strip.text = element_text(face = "bold",color="white"),
        strip.background = element_rect(fill="#1B9E77"),
        axis.text = element_text(size=10))+
  labs(y="PRECIO PROMEDIO",x="VENTAS")

modelos %>% 
  filter(cor<0,flag_12=="Si") %>% 
  head(3) %>%
  # head(9) %>% 
  unnest(elasticidad_df) %>% 
  filter(ventas>=5) %>% 
  ggplot(aes(y=ventas,x=precio_promedio))+
  geom_point()+
  geom_line()+
  # geom_smooth()+
  facet_wrap(~modelo,nrow = 3,scales = "free")+
  theme_bw()+
  labs(x="PRECIO PROMEDIO",y="VENTAS")

modelos %>% 
  filter(cor<0,flag_12=="Si") %>% 
  head(3) %>% 
  select(cor,flag_12,n_periodos,ventas_periodo)

  

```


```{r model}
# https://www.pricing.cl/conocimiento/elasticidad-precio-de-la-demanda/
# https://www.claseejecutiva.uc.cl/blog/articulos/como-calcular-la-elasticidad-de-la-demanda/
# https://conjointly.com/es/guides/understanding-price-elasticity-of-demand/

# df <- data.frame(ventas = c(10L, 9L),precio_promedio = c(100L, 120L)) # Elasticidad -0.5
df <- data.frame(ventas = c(20L, 12L),precio_promedio = c(100L, 120L)) # Elasticidad -2

# rlm_6 <- lm(ventas ~ precio_promedio, data = df)
# rlm_6 <- lm(log(ventas) ~ log(precio_promedio), data = df)
# rlm_6 <- rlm(ventas ~ precio_promedio, data = df)
rlm_6 <- rlm(log(ventas) ~ log(precio_promedio), data = df)

summary(rlm_6)
# summary(rlm_6)$r.squared
# rlm_6$coefficients[2]

rlm_6$coefficients[[1]]
rlm_6$coefficients[[2]]

# RLM
# 3 : Elasticidad: -5
# 4 : Elasticidad: -3
# 6 : Elasticidad  3
require(MASS)


modelos_12 <- modelos %>%
  filter(n_periodos >= 12) %>%
  filter(cor<0) %>% 
  
  mutate(ventas_model = map(elasticidad_df, function(x)
    rlm(ventas ~ precio_promedio, data = x))) %>% 
  
  mutate(precio_optimo = map_dbl(ventas_model, function(x) (-x$coefficients[[1]])/(2*x$coefficients[[2]]) )) %>% 
  
  mutate(venta_optimo= map_dbl(ventas_model,function(x) 
                  x$coefficients[[1]] +x$coefficients[[2]]*precio_optimo )) %>%
  
  mutate(elasticidad_model = map(elasticidad_df, function(x)
    rlm(log(ventas) ~ log(precio_promedio), data = x))) %>%
  
  mutate(elasticidad = map_dbl(elasticidad_model, function(x)
    abs(x$coefficients[2]) )) %>%
  
  mutate(lm_model = map(elasticidad_df,function(x) lm(ventas ~ precio_promedio,data = x)) ) %>%
  mutate(r2 = map_dbl(lm_model,function(x) summary(x)$r.squared )) %>% 
  
  mutate(r2=r2*100) %>% 
  # Funcion de ventas
  mutate(funcion_ventas = map_chr(ventas_model,function(x) 
    paste0(round(x$coefficients[[1]],2),round(x$coefficients[[2]],2),"*p") ) ) %>% 
  # Funcion de Ingresos
  mutate(funcion_ingresos = map_chr(ventas_model,function(x) 
    paste0(round(x$coefficients[[1]],2),"*p",round(x$coefficients[[2]],2),"*p^2") ) ) %>% 
  # Parametros 
  mutate(alfa0 = map_dbl(ventas_model,function(x) x$coefficients[[1]]   )  ) %>% 
  mutate(alfa1 = map_dbl(ventas_model,function(x) x$coefficients[[2]]   )  ) 
  
  
  
modelos_12 %>% 
  filter(r2>30)

modelos_12 %>% 
  dplyr::select(elasticidad,precio_optimo,venta_optimo,r2) %>% 
  filter(r2>30)
```


```{r model-celerio}

celerio <- modelos_12 %>% 
  filter(modelo=="JS2") %>% 
  ungroup()

b_0 <- celerio$ventas_model[[1]]$coefficients[[1]]
b_1 <- celerio$ventas_model[[1]]$coefficients[[2]]


b_0
b_1

# Curva

require(ggplot2)
p <- ggplot(data = data.frame(x = 0), mapping = aes(x = x))
p

fun <- function(x) b_0*x + b_1*x^2

p + stat_function(fun = fun,color="green") + 
  # scale_y_continuous(labels = comma(digits = 0))+
  xlim(0,15000)+
  ylim(0,400000)+
  theme_bw()

ggplot() +
  geom_function(fun = fun,
                colour = "green",
                lwd = 1,
                linetype = 1)+
  theme_bw()+
  scale_y_continuous(labels = scales::label_number(suffix = "k",
                                                   scale = 1e-3,
                                                   decimal.mark =  ".",
                                                   accuracy = 1),
                     limits = c(0,400000))+
  scale_x_continuous(labels = scales::label_number(suffix = "k",
                                                   scale = 1e-3,
                                                   decimal.mark =  ".",
                                                   accuracy = 1),
                     limits = c(0,15000))+
  geom_vline(xintercept = 6594.896,linetype="dashed")+
  labs(y="Ingresos($)",
       x="Precio SAP($)",
       title="Funcion de Precio SAP vs Ingresos")+
  theme(plot.title.position = "plot",
        plot.title= element_text(size=25),
        axis.text = element_text(size=12),
        axis.title.x = element_text(size=15),
        axis.title.y = element_text(size=15),
        )


```


```{r matrix-precio_optimo-venta_optima}

#Excluyendo los de 2 menores en correlacion ya que muestran precios exhorbitantes.
modelos_12 <- modelos_12 %>% 
  dplyr::select(elasticidad,precio_optimo,venta_optimo,n_periodos,cor,
                funcion_ventas,funcion_ingresos,alfa0,alfa1) %>% 
  filter(!modelo %in% c("CX70","CX-9")) %>% 
  ungroup() %>% 
  mutate(elasticidad_cat=ifelse(elasticidad>1,"Elastica","Inelastica")) %>% 
  mutate(elasticidad_orden = case_when(elasticidad<1~"[0-1>",
                                      elasticidad<3~"[1-3>",
                                      elasticidad<6~"[3-6>",
                                      elasticidad<9~"[6-9>",
                                      elasticidad<12~"[9-12>",
                                      )) %>% 
  mutate(elasticidad_orden=fct_reorder(elasticidad_orden,elasticidad,max)) 


names_modelos_extremos <- modelos_12 %>% 
  arrange(desc(venta_optimo)) %>% 
  slice(1:3) %>% 
  bind_rows(modelos_12 %>% 
  arrange(desc(precio_optimo)) %>% 
  slice(1:2)
  )

modelos_12 %>% 
  ggplot(aes(x=precio_optimo,y = venta_optimo,
             color=elasticidad_cat,
             size=elasticidad_orden,label=modelo))+
  geom_point()+
  scale_size_discrete(range = c(4,15))+
  theme_classic()+
  geom_label_repel(data = names_modelos_extremos,size=5)+
  labs(y="Ventas(u)",
       x="Precio Optimo($)",
       size="Rango Elasticidad",
       color="Tipo Demanda")+
  theme(plot.title.position = "plot",
        plot.title= element_text(size=25),
        axis.text = element_text(size=12),
        axis.title.x = element_text(size=15),
        axis.title.y = element_text(size=15),
        legend.position = c(.95, .95),
        legend.justification = c("right", "top"),
        legend.box.just = "right",
        legend.margin = margin(6, 6, 6, 6)
        )

modelos_12 %>% 
  write.csv("01.Data/Modelos_finales_elasticidad.csv")

# Enteder la elasticidad
# (Mayor elasticidad, mayor variacion de la demanda,
# menor elasticidad, menor variacion de la demanda.)

# Demanda inelastica entre 0 y 1 ,entonces la variación del precio afecta muy
# poco en la cantidad demandada

# Demanda elastica > 1, entonces la variación del precio afecta
# directamente a la cantidad demandada; es decir, si el precio sube la demanda baja drásticamente y viceversa 

# Demanda Unitaria = 1 ,entonces la variación del precio
# altera de manera igual a la demanda; por ejemplo, si el precio sube en 22% la
# demanda disminuye en 22%
 
# Matriz Precios y Demanda Optimo color Elasticidad(Inelastica, elastica)


modelos_12$elasticidad %>% sort


prueba <- modelos_12 %>% 
  mutate(r2 = map_dbl(lm_model,function(x) summary(x)$r.squared ))s


prueba %>% 
  dplyr::select(elasticidad_model,cor,elasticidad,r2)

# Graficas de vehiculos precio demanda
# Que vehiculos tienen elasiticidad  y que no.
# Tomar ventaja de las elasticidad ver que vehiculos son sensibles y que no.



```
